### ISSUE TITLE
Getting error while running meitar/jekyll-builder-for-github-pages-action@master

### ISSUE THREAD

**Issue by maslyankov** [meitar/jekyll-builder-for-github-pages-action#2]
After running the action I get this error:
```
curl: (22) The requested URL returned error: 404 Not Found
/usr/local/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' 
(JSON::ParserError)
 	from /usr/local/lib/ruby/2.6.0/json/common.rb:156:in `parse'
	from -e:1:in `<main>'
```
I have setup as in the readme (token was created and stored as a secret as instructed)

yml file :
```
jobs:
  build-and-publish:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    steps:
      # Checkout the source from the `main` branch.
      - uses: actions/checkout@v2

      # Invoke this action against the newly checked out source code.
      - uses: meitar/jekyll-builder-for-github-pages-action@master
        with:
          # Provide this action with your repository's `GH_PAGES_TOKEN`
          # "Secret" variable. This should be the value of a personal
          # access token granted, at a minimum, the `public_repo` and
          # the `repo_deployment` scopes needed to deploy to GH Pages.
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
          # Shouldn't be neccessary but..
          gh_pages_publishing_source: gh-pages
```
Thank you.
